"""Add Abstract Modal user id

Revision ID: 1fb1c649985d
Revises: 5edba1075e82
Create Date: 2023-06-03 00:38:49.302680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb1c649985d'
down_revision = '5edba1075e82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'abstracts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abstracts', type_='foreignkey')
    op.drop_column('abstracts', 'user_id')
    # ### end Alembic commands ###
