"""Add Abstract update upgrade

Revision ID: 403a575c6e2f
Revises: 1fb1c649985d
Create Date: 2023-06-03 00:48:23.339985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403a575c6e2f'
down_revision = '1fb1c649985d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
