"""Add description field for Workspace 2

Revision ID: 45835577bb1a
Revises: 08f586bbab0e
Create Date: 2023-05-29 04:05:04.192044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45835577bb1a'
down_revision = '08f586bbab0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('description', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'description')
    # ### end Alembic commands ###
