"""Add is_deleted field for folder and abstract

Revision ID: 544bbbae2b90
Revises: dfc2b7ec549b
Create Date: 2023-09-14 10:02:16.569834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544bbbae2b90'
down_revision = 'dfc2b7ec549b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abstracts', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('folders', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'is_deleted')
    op.drop_column('abstracts', 'is_deleted')
    # ### end Alembic commands ###
