"""Add is_deleted field for folder and abstract

Revision ID: 5ea9f7ca18e2
Revises: 544bbbae2b90
Create Date: 2023-09-14 15:06:05.068306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea9f7ca18e2'
down_revision = '544bbbae2b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
