"""Add cascade delete workspace-folder

Revision ID: 6ee6aeddd794
Revises: 5ea9f7ca18e2
Create Date: 2023-09-14 15:08:47.582730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee6aeddd794'
down_revision = '5ea9f7ca18e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folders_workspace_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_workspace_id_fkey', 'folders', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
