"""a

Revision ID: 728deb7823e3
Revises: 8add41a891fc
Create Date: 2023-09-30 13:41:47.204987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '728deb7823e3'
down_revision = '8add41a891fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
