"""Add workspaces

Revision ID: 78b508c63ed2
Revises: c63e7a7cc3b9
Create Date: 2023-05-28 18:20:36.834502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b508c63ed2'
down_revision = 'c63e7a7cc3b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
