"""Add nullable url open

Revision ID: 88b7639345f9
Revises: bffb5af1e0ce
Create Date: 2023-06-02 13:15:05.088822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b7639345f9'
down_revision = 'bffb5af1e0ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'url_open',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'url_open',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
