"""Add one photo field

Revision ID: 8add41a891fc
Revises: e112e74a946e
Create Date: 2023-09-21 11:58:58.527692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8add41a891fc'
down_revision = 'e112e74a946e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces_avatars', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_constraint('workspaces_avatars_high_photo_url_key', 'workspaces_avatars', type_='unique')
    op.drop_constraint('workspaces_avatars_low_photo_url_key', 'workspaces_avatars', type_='unique')
    op.create_unique_constraint(None, 'workspaces_avatars', ['photo_url'])
    op.drop_column('workspaces_avatars', 'low_photo_url')
    op.drop_column('workspaces_avatars', 'high_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces_avatars', sa.Column('high_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('workspaces_avatars', sa.Column('low_photo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workspaces_avatars', type_='unique')
    op.create_unique_constraint('workspaces_avatars_low_photo_url_key', 'workspaces_avatars', ['low_photo_url'])
    op.create_unique_constraint('workspaces_avatars_high_photo_url_key', 'workspaces_avatars', ['high_photo_url'])
    op.drop_column('workspaces_avatars', 'photo_url')
    # ### end Alembic commands ###
