"""a 2

Revision ID: a44545b2efdf
Revises: e174d96a8542
Create Date: 2023-09-30 14:54:22.793743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44545b2efdf'
down_revision = 'e174d96a8542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
