"""datetime update

Revision ID: ba1d073a4549
Revises: 403a575c6e2f
Create Date: 2023-06-03 15:00:44.064420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1d073a4549'
down_revision = '403a575c6e2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
