"""add

Revision ID: d3616a12a2a1
Revises: 6ee6aeddd794
Create Date: 2023-09-16 11:07:08.500124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3616a12a2a1'
down_revision = '6ee6aeddd794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'folders', ['workspace_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='unique')
    # ### end Alembic commands ###
