"""unique user_id

Revision ID: e1e40b5c41ee
Revises: c2ef48e4c234
Create Date: 2023-05-28 01:12:02.324964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e40b5c41ee'
down_revision = 'c2ef48e4c234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
