"""add 2

Revision ID: fe141384f5b5
Revises: d3616a12a2a1
Create Date: 2023-09-19 08:04:48.856516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe141384f5b5'
down_revision = 'd3616a12a2a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('abstracts_folder_id_fkey', 'abstracts', type_='foreignkey')
    op.create_foreign_key(None, 'abstracts', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('folders_workspace_id_key', 'folders', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('folders_workspace_id_key', 'folders', ['workspace_id'])
    op.drop_constraint(None, 'abstracts', type_='foreignkey')
    op.create_foreign_key('abstracts_folder_id_fkey', 'abstracts', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###
